### ISSUE TITLE
[Bug] Insight 可能导致 Koishi 完全崩溃

### ISSUE THREAD

**Issue by SuXinxian** [HydroGest/YesImBot#11]
[2024-08-10-7.log](https://github.com/user-attachments/files/16570686/2024-08-10-7.log)
![image](https://github.com/user-attachments/assets/9116de44-f66c-48ef-b1ce-526df6fe5958)
在运行状态修改这三个值，再点击重载，会发生严重的崩溃。这个bug是可复现的，因此我付出了重装两次koishi，从头配置两次的惨痛代价。希望能找出问题并修复

**Comment by HydroGest** [comment]
请检查  insight 插件是否是最新版本
