### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by L7040** [HydroGest/YesImBot#13]
根据教程填写后无法正常使用![aee4dda34da53a4a21752ec0a003231e](https://github.com/user-attachments/assets/77dd2463-a3c8-468a-ae93-45f12101e4d7)

**Comment by HydroGest** [comment]
截屏一下你的 prompt 相关配置

**Comment by L7040** [comment]
全部都是默认没有修改![Uploading 5ac6e02cd07ce915183ebec3d5d970a3.png…]()

**Comment by HydroGest** [comment]
更新到新版本
