### ISSUE TITLE
如果想要在Discord/Telegream/Kook等平台使用的话要怎么添加群号呢

### ISSUE THREAD

**Issue by 123xzxc** [HydroGest/YesImBot#14]
如果想要在Discord/Telegream/Kook等平台使用的话要怎么添加群号呢
目前好像只有QQ支持，有办法让其支持其他平台么
(而且现在qq官方api还没法接收at以外的数据，相当于没法用，想转平台发现不支持）

**Comment by HydroGest** [comment]
先安装一下，收到消息后会在 log 里说明的
