### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'APIType')

### ISSUE THREAD

**Issue by XUANHLGG** [HydroGest/YesImBot#17]
启动后在群聊内发送20条消息触发，出现报错 TypeError: Cannot read properties of undefined (reading 'APIType')
![image](https://github.com/user-attachments/assets/e1a64aad-9fbc-4562-bea4-f33038dc96b6)
看样子是无法读取APIType？配置↑
感谢

**Comment by HydroGest** [comment]
配置没配完。截屏中的是验证器的 API 配置，但是这不是必填项。必填的是 LLM API 设置。请重新检查配置项
