### ISSUE TITLE
使用QQ官方接口启用插件后没有效果

### ISSUE THREAD

**Issue by LBEILC** [HydroGest/YesImBot#4]
使用qq接口，启用插件后在对应群聊发多少信息也没有效果，具体配置如下
![image](https://github.com/user-attachments/assets/f49421df-ed7e-45e8-9a56-7a644a5da78d)
启动后koishi中的日志如下，日志中也没有报错啥的
![image](https://github.com/user-attachments/assets/eef08ecb-a77a-493f-b4df-d0c0aa827bdb)

**Comment by HydroGest** [comment]
是否同时启用了 neko 插件？试着关掉可能不兼容的插件试试?

**Comment by HydroGest** [comment]
试着配置里面打开 debug

**Comment by LBEILC** [comment]
> 试着配置里面打开 debug

插件配置中的debag模式已经开启，但是日志里还是什么都没有，插件只开了yesimbot，也还是不行

**Comment by Dispure** [comment]
> > 试着配置里面打开 debug
> 
> 插件配置中的debag模式已经开启，但是日志里还是什么都没有，插件只开了yesimbot，也还是不行

确认一下 Allowed Groups 有没有填对?

如果插件运行正常并且开启了 `DebugAsInfo`，收到消息之后会有控制台输出。看现在这种情况有可能是群号填错了。

**Comment by LBEILC** [comment]
> > > 试着配置里面打开 debug
> > 
> > 
> > 插件配置中的debag模式已经开启，但是日志里还是什么都没有，插件只开了yesimbot，也还是不行
> 
> 确认一下 Allowed Groups 有没有填对?
> 
> 如果插件运行正常并且开启了 `DebugAsInfo`，收到消息之后会有控制台输出。看现在这种情况有可能是群号填错了。
> 
> 再不济, 重启 Koishi 试试。

群号如图
![image](https://github.com/user-attachments/assets/f41af010-0b31-4aee-bf55-f6bf7a55a0d4)

插件配置中群号：
![image](https://github.com/user-attachments/assets/7233e9ff-7df9-4cf8-b92d-46ffef86deb2)
插件运行正常并且开启了 DebugAsInfo，Koishi日志中还是没东西
已经重启过koishi

**Comment by HydroGest** [comment]
其他插件是可以收到群消息的吧？

**Comment by LBEILC** [comment]
> 其他插件是可以收到群消息的吧？

使用过oob和knj插件，可以顺利接收到群聊中的消息和私聊消息

**Comment by HydroGest** [comment]
沙盒能过吗

**Comment by LBEILC** [comment]
> 沙盒能过吗

试了一下沙盒也没有反应

**Comment by HydroGest** [comment]
我明白了，将在下一个更新添加对qq官方接口适配器的支持。

**Comment by CheFng** [comment]
我遇到了同样的问题，期待问题解决

**Comment by HydroGest** [comment]
看看是否解决。

**Comment by LBEILC** [comment]
> 看看是否解决。

目前在沙盒和私聊中或者群聊直接@机器人的情况下已经可以接收消息，但是channeId和q群号码不一样，成功接收到消息后无法回复，报以下错误：
![image](https://github.com/user-attachments/assets/ec68b9fa-a8cb-408e-96a6-d2a0df219c4e)

**Comment by LBEILC** [comment]
将群聊的channeId（36F62DD2AF52D5FE0FE540850AB5AB87）添加到插件中，在群聊中@机器人时报错
![image](https://github.com/user-attachments/assets/6c6bc8e9-3bab-4df0-95a9-9ad4b500111c)
![image](https://github.com/user-attachments/assets/6006aa66-28d7-4e66-a2d2-69f6cb10f261)

**Comment by HydroGest** [comment]
收到

**Comment by LBEILC** [comment]
> 能用 1.1.8 重新试试。
> 
> QQ 官方接口机器人无法主动接收消息。
> 
> 只有 @ 机器人的消息才能被接收。

![image](https://github.com/user-attachments/assets/bb53ecd6-900e-4a15-9240-ad6ba84d75dc)
更新了之后配置页面消失了，尝试重启软件，删除依赖，回退版本，都没法正常加载配置页面，其他插件配置页面均正常

**Comment by HydroGest** [comment]
s

> > 能用 1.1.8 重新试试。
> > QQ 官方接口机器人无法主动接收消息。
> > 只有 @ 机器人的消息才能被接收。
> 
> ![image](https://private-user-images.githubusercontent.com/74463574/351990870-bb53ecd6-900e-4a15-9240-ad6ba84d75dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTYxNzgsIm5iZiI6MTcyMTg5NTg3OCwicGF0aCI6Ii83NDQ2MzU3NC8zNTE5OTA4NzAtYmI1M2VjZDYtOTAwZS00YTE1LTkyNDAtYWQ2YmE4NGQ3NWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMDlmN2RhYWVjMGNlMTE0YmI1NjUxM2I3ZjEzNDgwMTgwMDIxNDk2OWY1NzViOTNkYTAzNzRmNzc4NDI2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-eyL6g_rWSXhcBug6qWMw0zEDO4Zktqhhy_leG4xWY) 更新了之后配置页面消失了，尝试重启软件，删除依赖，回退版本，都没法正常加载配置页面，其他插件配置页面均正常

1.1.9 已发布

**Comment by LBEILC** [comment]
> s
> 
> > > 能用 1.1.8 重新试试。
> > > QQ 官方接口机器人无法主动接收消息。
> > > 只有 @ 机器人的消息才能被接收。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/74463574/351990870-bb53ecd6-900e-4a15-9240-ad6ba84d75dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTYxNzgsIm5iZiI6MTcyMTg5NTg3OCwicGF0aCI6Ii83NDQ2MzU3NC8zNTE5OTA4NzAtYmI1M2VjZDYtOTAwZS00YTE1LTkyNDAtYWQ2YmE4NGQ3NWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMDlmN2RhYWVjMGNlMTE0YmI1NjUxM2I3ZjEzNDgwMTgwMDIxNDk2OWY1NzViOTNkYTAzNzRmNzc4NDI2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-eyL6g_rWSXhcBug6qWMw0zEDO4Zktqhhy_leG4xWY) 更新了之后配置页面消失了，尝试重启软件，删除依赖，回退版本，都没法正常加载配置页面，其他插件配置页面均正常
> 
> 1.1.9 已发布

QQ 官方接口机器人无法主动接收消息的话，一般使用什么接口呢，onebot吗

**Comment by HydroGest** [comment]
> > s
> > > > 能用 1.1.8 重新试试。
> > > > QQ 官方接口机器人无法主动接收消息。
> > > > 只有 @ 机器人的消息才能被接收。
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/74463574/351990870-bb53ecd6-900e-4a15-9240-ad6ba84d75dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTYxNzgsIm5iZiI6MTcyMTg5NTg3OCwicGF0aCI6Ii83NDQ2MzU3NC8zNTE5OTA4NzAtYmI1M2VjZDYtOTAwZS00YTE1LTkyNDAtYWQ2YmE4NGQ3NWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMDlmN2RhYWVjMGNlMTE0YmI1NjUxM2I3ZjEzNDgwMTgwMDIxNDk2OWY1NzViOTNkYTAzNzRmNzc4NDI2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-eyL6g_rWSXhcBug6qWMw0zEDO4Zktqhhy_leG4xWY) 更新了之后配置页面消失了，尝试重启软件，删除依赖，回退版本，都没法正常加载配置页面，其他插件配置页面均正常
> > 
> > 
> > 1.1.9 已发布
> 
> QQ 官方接口机器人无法主动接收消息的话，一般使用什么接口呢，onebot吗

是的。你可以了解一下 LLOneBot或NapCat

**Comment by HydroGest** [comment]
> > s
> > > > 能用 1.1.8 重新试试。
> > > > QQ 官方接口机器人无法主动接收消息。
> > > > 只有 @ 机器人的消息才能被接收。
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/74463574/351990870-bb53ecd6-900e-4a15-9240-ad6ba84d75dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTYxNzgsIm5iZiI6MTcyMTg5NTg3OCwicGF0aCI6Ii83NDQ2MzU3NC8zNTE5OTA4NzAtYmI1M2VjZDYtOTAwZS00YTE1LTkyNDAtYWQ2YmE4NGQ3NWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMDlmN2RhYWVjMGNlMTE0YmI1NjUxM2I3ZjEzNDgwMTgwMDIxNDk2OWY1NzViOTNkYTAzNzRmNzc4NDI2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-eyL6g_rWSXhcBug6qWMw0zEDO4Zktqhhy_leG4xWY) 更新了之后配置页面消失了，尝试重启软件，删除依赖，回退版本，都没法正常加载配置页面，其他插件配置页面均正常
> > 
> > 
> > 1.1.9 已发布
> 
> QQ 官方接口机器人无法主动接收消息的话，一般使用什么接口呢，onebot吗

所有报错消失了嘛

**Comment by LBEILC** [comment]
> > > s
> > > > > 能用 1.1.8 重新试试。
> > > > > QQ 官方接口机器人无法主动接收消息。
> > > > > 只有 @ 机器人的消息才能被接收。
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/74463574/351990870-bb53ecd6-900e-4a15-9240-ad6ba84d75dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTYxNzgsIm5iZiI6MTcyMTg5NTg3OCwicGF0aCI6Ii83NDQ2MzU3NC8zNTE5OTA4NzAtYmI1M2VjZDYtOTAwZS00YTE1LTkyNDAtYWQ2YmE4NGQ3NWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMDlmN2RhYWVjMGNlMTE0YmI1NjUxM2I3ZjEzNDgwMTgwMDIxNDk2OWY1NzViOTNkYTAzNzRmNzc4NDI2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-eyL6g_rWSXhcBug6qWMw0zEDO4Zktqhhy_leG4xWY) 更新了之后配置页面消失了，尝试重启软件，删除依赖，回退版本，都没法正常加载配置页面，其他插件配置页面均正常
> > > 
> > > 
> > > 1.1.9 已发布
> > 
> > 
> > QQ 官方接口机器人无法主动接收消息的话，一般使用什么接口呢，onebot吗
> 
> 所有报错消失了嘛

现在不报错了，但是qq还是没接收到消息，我看我的后台已经成功发送openai的网络请求了

**Comment by LBEILC** [comment]
> > > s
> > > > > 能用 1.1.8 重新试试。
> > > > > QQ 官方接口机器人无法主动接收消息。
> > > > > 只有 @ 机器人的消息才能被接收。
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/74463574/351990870-bb53ecd6-900e-4a15-9240-ad6ba84d75dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTYxNzgsIm5iZiI6MTcyMTg5NTg3OCwicGF0aCI6Ii83NDQ2MzU3NC8zNTE5OTA4NzAtYmI1M2VjZDYtOTAwZS00YTE1LTkyNDAtYWQ2YmE4NGQ3NWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4MjQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMDlmN2RhYWVjMGNlMTE0YmI1NjUxM2I3ZjEzNDgwMTgwMDIxNDk2OWY1NzViOTNkYTAzNzRmNzc4NDI2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-eyL6g_rWSXhcBug6qWMw0zEDO4Zktqhhy_leG4xWY) 更新了之后配置页面消失了，尝试重启软件，删除依赖，回退版本，都没法正常加载配置页面，其他插件配置页面均正常
> > > 
> > > 
> > > 1.1.9 已发布
> > 
> > 
> > QQ 官方接口机器人无法主动接收消息的话，一般使用什么接口呢，onebot吗
> 
> 所有报错消失了嘛

![image](https://github.com/user-attachments/assets/16839bf3-cd7b-4283-a9d3-644286347922)
![image](https://github.com/user-attachments/assets/1a401704-378e-485b-848e-a40b59e40525)

**Comment by LBEILC** [comment]
> 另外，推荐使用 LLOneBot.

说的对，还是用onebot吧，我试了一下，onebot有时候也会接收不到消息，每个号的情况都不一样，不知道为啥
