### ISSUE TITLE
[bug] 生产环境下 data 的获取路径有问题

### ISSUE THREAD

**Issue by HydroGest** [HydroGest/YesImBot#53]
![Image_347486621596870.jpg](https://github.com/user-attachments/assets/772140be-d0ad-4713-b871-cf01cb8bb2f1)

应为 `node_modules/koishi-plugin-yesimbot/data/emojis.json`
但目前出现了在 `node_modules/data/emojis.json` 获取的情况。

**Comment by Touch-Night** [comment]
`const emojisFile = path.join(__dirname, '../../data/emojis.json');` 原本在处于项目二级目录的文件content.ts中，但构建后，它到了处在项目一级目录下的index.js中，导致相对路径错误。怎么1.6.0没有这个问题？
