### ISSUE TITLE
[bug] 打开bot自身消息上报时，消息队列会写入重复的消息

### ISSUE THREAD

**Issue by MiaowFISH** [HydroGest/YesImBot#59]
使用napcat作为后端，并开启机器人自身消息上报。bot发送的消息会被两次添加到queue.json中

这两处都对消息队列进行了更新
https://github.com/HydroGest/YesImBot/blob/d128cc0ea6c0f6aa1d2aead1f0650f56a2068be6/src/index.ts#L67-L84

https://github.com/HydroGest/YesImBot/blob/d128cc0ea6c0f6aa1d2aead1f0650f56a2068be6/src/index.ts#L402

**Comment by Touch-Night** [comment]
写了一个比较折衷的解决方案https://github.com/HydroGest/YesImBot/pull/57/commits/4622e3317d3b02de9250398894cadd97e1ce5964
