### ISSUE TITLE
[Feature Request] 关于项目 Logo

### ISSUE THREAD

**Issue by MizuAsaka** [HydroGest/YesImBot#6]
前面花了点时间，重绘了一下 Athena 的 Logo，不知道作者大大意下如何 ()

![Athena Logo](https://github.com/user-attachments/assets/bfecf956-4409-4d7e-be24-c154b5a7f191)

(如果需要 SVG 版 请说一下)

**Comment by HydroGest** [comment]
www好好看！！！
就这个了

**Comment by HydroGest** [comment]
能给 svg 嘛
