### ISSUE TITLE
触发回复后如果没有及时处理会导致短时间内多次调用

### ISSUE THREAD

**Issue by NFS688** [HydroGest/YesImBot#60]
![image](https://github.com/user-attachments/assets/918abd57-7b84-4d6d-9614-939e8ea417cb)

如上图，达到触发条件后，第一条消息没有及时处理导致连续重复调用了4次
之前1.6就没这种情况

**Comment by Touch-Night** [comment]
解决了https://github.com/HydroGest/YesImBot/pull/57/commits/2aff7298e0676ae278da40003341a6b9948bf8fe
